// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaewecelzumseollzbcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhZXdlY2VsenVtc2VvbGx6YmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTk3MzksImV4cCI6MjA3MjM5NTczOX0.37VX0ohZxcPz4a_XEnyKkjSPdzipvAWjLPzmBaLtZb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});